version: 0.2 

phases: 
    install:
        commands:
            - echo install package php
            - apt-get install php-zip php-gd
    pre_build:
        commands:
            - echo build package php
            - composer install
            - cd ~/webroot/grav
            - bin/grav install
    build:
        commands:
            - echo unit testing 
            - composer test
artifacts:
    files: 
        - grey/data.zip