version: 0.2 

phases: 
    install:
        commands:
            - composer install
    build:
        commands:
            - echo build started on `date`
            - composer test
artifacts:
    files: 
        - grey/data.zip