version: 0.2 

phases: 
    install:
        commands:
            - composer install --no-dev -o
            - cd ~/webroot/grav
            - bin/grav install
    build:
        commands:
            - echo build started on `date`
            - composer test
artifacts:
    files: 
        - grey/data.zip